default_language_version:
    python: python3.6
repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.7.0
    hooks:
    - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
    - id: isort
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
      args: ["--max-line-length=88"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.670"
    hooks:
    - id: mypy
  - repo: local
    hooks:
      - id: pytest
        name: Check pytest unit tests pass
        entry: pytest
        pass_filenames: false
        language: system
        types: [python]
