language: python
python:
  - "3.6"
before_install:
  - sudo apt-get install libimage-exiftool-per
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - pytest
notifications:
  email:
    on_success: never
    on_failure: never
