version: '3'
services:
  kamera_server:
    container_name: kamera_server
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - app_version
    command: "venv/bin/python -m kamera --mode server --port 5001"
    expose:
      - 5001
    ports:
      - "5001:5001"
    depends_on:
      - redis
    networks:
      - kamera_network
      - nginx_network

  kamera_worker:
    container_name: kamera_worker
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - app_version
    command: "venv/bin/python -m kamera --mode worker"
    depends_on:
      - redis
    networks:
      - kamera_network

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    env_file:
      - .env
    entrypoint: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - kamera_network

networks:
  nginx_network:
    external:
      name: nginx_default
  kamera_network: ~
